_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  breakpoint: 0
  checklistapi: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  core_event_dispatcher: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  ebt_core: 0
  editor: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_lb: 0
  gin_toolbar: 0
  help: 0
  history: 0
  hook_event_dispatcher: 0
  image: 0
  jquery_ui: 0
  layout_bg: 0
  layout_bg_bricks: 0
  layout_builder: 0
  layout_builder_blocks: 0
  layout_builder_component_attributes: 0
  layout_builder_kit: 0
  layout_builder_tabs: 0
  layout_custom_section_classes: 0
  layout_discovery: 0
  layout_library: 0
  link: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  responsive_menus: 0
  search: 0
  seo_checklist: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twbstools: 0
  update: 0
  user: 0
  views_ui: 0
  vvjs: 0
  webform: 0
  webform_attachment: 0
  webform_image_select: 0
  webform_node: 0
  webform_submission_log: 0
  webform_ui: 0
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  starterkit_theme: 0
  basecore: 0
  bootstrap_business: 0
  gin: 0
  sandpiper_landscapes: 0
profile: standard
