features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://SPL_Logo_Name_Site2026_0.png'
favicon:
  use_default: 1
breadcrumb_separator: fa-angle-double-right
scroll_to_top_display: 1
scroll_to_top_icon: fa-angles-up
mobile_menu_widget_display: 1
mobile_menu_widget_sticky: 1
bootstrap_remote_type: local
global_corner_style: mt-style-sharp
button_corner_style: mt-style-button-global
form_corner_style: mt-style-form-global
image_corner_style: mt-style-image-global
menu_corner_style: mt-style-menu-global
custom_elements_corner_style: mt-style-custom-global
color_scheme: green
links_style: mt-link-style-animated-underline-1
page_container_border: 1
animations_state: 1
background_pattern: none
slideout_background_color: region--bright-background
slideout_side: right
slideout_mobile_menu_display: 0
slideout_touch_swipe: 0
slideout_blocks_paddings: 0
slideout_region_paddings: 0
header_top_highlighted_layout_container: container
header_top_highlighted_background_color: region--accent-background
header_top_highlighted_animation_effect: fadeIn
header_top_highlighted_blocks_paddings: 0
header_top_highlighted_region_paddings: 1
header_top_layout_container: container-fluid
header_top_background_color: region--accent-background
header_top_animation_effect: no-animation
header_top_blocks_paddings: 0
header_top_region_paddings: 0
header_layout_container: container
header_background_color: region--accent-background
fixed_header: 1
fixed_header_behavior: fixed-header-enabled--scroll-up
header_blocks_paddings: 1
header_region_paddings: 1
header_horizontal_paddings: 1
header_background_image_state: 0
hero_top_layout_container: container
hero_top_background_color: region--tint-background
hero_top_animation_effect: no-animation
hero_top_blocks_paddings: 0
hero_top_region_paddings: 0
hero_layout_container: container
hero_background_color: region--bright-background
hero_animation_effect: no-animation
hero_blocks_paddings: 1
hero_region_paddings: 1
banner_layout_container: container-fluid
banner_background_color: region--bright-background
banner_blocks_paddings: 1
banner_region_paddings: 1
content_top_layout_container: container
content_top_background_color: region--bright-background
content_top_animation_effect: fadeIn
content_top_blocks_paddings: 0
content_top_region_paddings: 0
content_top_highlighted_layout_container: container-fluid
content_top_highlighted_separator: region--no-separator
content_top_highlighted_background_color: region--accent-background
content_top_highlighted_animation_effect: fadeIn
content_top_highlighted_blocks_paddings: 0
content_top_highlighted_region_paddings: 1
main_content_layout_container: container
main_content_separator: region--no-separator
main_content_background_color: region--tint-background
main_content_animation_effect: no-animation
main_content_blocks_paddings: 0
main_content_region_paddings: 0
sidebar_first_animation_effect: fadeIn
sidebar_first_blocks_paddings: 0
sidebar_first_region_paddings: 0
sidebar_second_animation_effect: fadeIn
sidebar_second_blocks_paddings: 0
sidebar_second_region_paddings: 0
content_bottom_layout_container: container
content_bottom_separator: region--no-separator
content_bottom_background_color: region--accent-background
content_bottom_animation_effect: fadeIn
content_bottom_blocks_paddings: 0
content_bottom_region_paddings: 0
content_bottom_highlighted_layout_container: container
content_bottom_highlighted_separator: region--no-separator
content_bottom_highlighted_background_color: region--bright-background
content_bottom_highlighted_animation_effect: fadeIn
content_bottom_highlighted_blocks_paddings: 0
content_bottom_highlighted_region_paddings: 1
featured_top_layout_container: container
featured_top_separator: region--no-separator
featured_top_background_color: region--accent-background
featured_top_animation_effect: fadeIn
featured_top_blocks_paddings: 0
featured_top_region_paddings: 0
featured_layout_container: container
featured_separator: region--no-separator
featured_background_color: region--tint-background
featured_animation_effect: fadeIn
featured_blocks_paddings: 1
featured_region_paddings: 0
featured_bottom_layout_container: container-fluid
featured_bottom_separator: region--no-separator
featured_bottom_background_color: region--default-background
featured_bottom_animation_effect: no-animation
featured_bottom_blocks_paddings: 0
featured_bottom_region_paddings: 0
sub_featured_layout_container: container-fluid
sub_featured_separator: region--no-separator
sub_featured_background_color: region--accent-background
sub_featured_animation_effect: no-animation
sub_featured_blocks_paddings: 0
sub_featured_region_paddings: 0
highlighted_top_layout_container: container
highlighted_top_separator: region--no-separator
highlighted_top_background_color: region--accent-background
highlighted_top_animation_effect: fadeIn
highlighted_top_blocks_paddings: 0
highlighted_top_region_paddings: 0
highlighted_layout_container: container-fluid
highlighted_separator: region--no-separator
highlighted_background_color: region--bright-background
highlighted_animation_effect: fadeIn
highlighted_blocks_paddings: 0
highlighted_region_paddings: 0
footer_top_layout_container: container
footer_top_separator: region--no-separator
footer_top_background_color: region--tint-background
footer_top_animation_effect: no-animation
footer_top_blocks_paddings: 0
footer_top_region_paddings: 0
footer_layout_container: container
footer_separator: region--no-separator
footer_background_color: region--accent-background
footer_animation_effect: no-animation
footer_blocks_paddings: 0
footer_region_paddings: 0
footer_bottom_layout_container: container
footer_bottom_separator: region--no-separator
footer_bottom_background_color: region--tint-background
footer_bottom_blocks_paddings: 0
footer_bottom_region_paddings: 0
subfooter_top_layout_container: container
subfooter_top_separator: region--no-separator
subfooter_top_background_color: region--tint-background
subfooter_top_blocks_paddings: 0
subfooter_top_region_paddings: 0
subfooter_layout_container: container
subfooter_separator: region--no-separator
subfooter_background_color: region--accent-background
subfooter_blocks_paddings: 0
subfooter_region_paddings: 0
sticky_footer_layout_container: container
sticky_footer_background_color: region--tint-background
sticky_footer_blocks_paddings: 0
sticky_footer_region_paddings: 0
sticky_footer_trigger_text: ''
total_node_views: 1
reading_time: 1
font_resize: 1
post_progress: 1
sticky_side: 1
share_links: 1
print_button: 1
share_links_print_position: bottom
layout_mode: wide
font_title: ''
sitename_font_family: sff-46
slogan_font_family: slff-46
headings_font_family: hff-46
headings_wide_spacing: 0
paragraph_font_family: pff-46
paragraph_responsive_typography: 0
rs_slideshow_fullscreen_effect: random
rs_slideshow_fullscreen_effect_time: '10'
rs_slideshow_fullscreen_navigation_style: bullets
rs_slideshow_fullscreen_bullets_position: right
rs_slideshow_fullscreen_touch_swipe: 1
transparent_header_state: 1
transparent_header_opacity: '0'
inverted_header_state: 1
rs_slideshow_fullwidth_effect: random
rs_slideshow_fullwidth_effect_time: '10'
rs_slideshow_fullwidth_initial_height: '500'
rs_slideshow_fullwidth_auto_height: 0
rs_slideshow_fullwidth_navigation_style: bullets
rs_slideshow_fullwidth_bullets_position: right
rs_slideshow_fullwidth_touch_swipe: 1
rs_slideshow_boxedwidth_effect: random
rs_slideshow_boxedwidth_effect_time: '10'
rs_slideshow_boxedwidth_initial_height: '500'
rs_slideshow_boxedwidth_auto_height: 0
rs_slideshow_boxedwidth_navigation_style: bullets
rs_slideshow_boxedwidth_bullets_position: center
rs_slideshow_boxedwidth_touch_swipe: 1
rs_slideshow_internal_effect: fade
rs_slideshow_internal_layout: fullscreen
rs_slideshow_internal_effect_time: '10'
rs_slideshow_internal_initial_height: '450'
rs_slideshow_internal_auto_height: 0
rs_slideshow_internal_navigation_style: bullets
rs_slideshow_internal_bullets_position: left
rs_slideshow_internal_touch_swipe: 1
rs_slideshow_internal_carousel_effect: fade
rs_slideshow_internal_carousel_initial_height: '540'
rs_slideshow_internal_carousel_bullets_position: center
rs_slideshow_internal_carousel_touch_swipe: 1
rs_slideshow_caption_opacity: '0'
rs_slideshow_background_opacity: '50'
flexslider_main_effect: fade
flexslider_main_effect_time: '5'
in_page_slider_effect: fade
breaking_effect: fade
breaking_effect_time: '5'
owl_products_autoplay: 0
owl_products_effect_time: '5'
owl_albums_autoplay: 0
owl_albums_effect_time: '5'
owl_team_members_autoplay: 0
owl_team_members_effect_time: '5'
owl_articles_autoplay: 0
owl_articles_effect_time: '5'
owl_testimonials_autoplay: 0
owl_testimonials_effect_time: '5'
owl_related_nodes_autoplay: 0
owl_related_nodes_effect_time: '5'
owl_collections_autoplay: 0
owl_collections_effect_time: '5'
in_page_navigation_offset: '69'
banner_id: banner
hero_top_id: hero-top
hero_id: hero
content_top_id: content-top
content_top_highlighted_id: content-top-highlighted
main_content_id: main-content
content_bottom_highlighted_id: content-bottom-highlighted
content_bottom_id: content-bottom
featured_top_id: featured-top
featured_id: featured
featured_bottom_id: featured-bottom
sub_featured_id: sub-featured
highlighted_top_id: highlighted-top
highlighted_id: highlighted
footer_top_id: footer-top
footer_id: footer
footer_bottom_id: footer-bottom
subfooter_top_id: subfooter-top
subfooter_id: subfooter
isotope_layout_mode: fitRows
isotope_filters_text: All
google_maps_key: your_google_maps_key
purechat_display: 0
purechat_key: ''
enable_pwa: 0
